// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	Credentials
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ImageType int32

const (
	ImageType_FILE  ImageType = 0
	ImageType_IMAGE ImageType = 1
	ImageType_URL   ImageType = 2
)

var ImageType_name = map[int32]string{
	0: "FILE",
	1: "IMAGE",
	2: "URL",
}
var ImageType_value = map[string]int32{
	"FILE":  0,
	"IMAGE": 1,
	"URL":   2,
}

func (x ImageType) String() string {
	return proto.EnumName(ImageType_name, int32(x))
}
func (ImageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Credentials struct {
	Algolia_AMI string `protobuf:"bytes,1,opt,name=Algolia_AMI,json=algoliaAMI" json:"Algolia_AMI,omitempty"`
	APP_Code    string `protobuf:"bytes,2,opt,name=APP_Code,json=aPPCode" json:"APP_Code,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Credentials) GetAlgolia_AMI() string {
	if m != nil {
		return m.Algolia_AMI
	}
	return ""
}

func (m *Credentials) GetAPP_Code() string {
	if m != nil {
		return m.APP_Code
	}
	return ""
}

func init() {
	proto.RegisterType((*Credentials)(nil), "protos.Credentials")
	proto.RegisterEnum("protos.ImageType", ImageType_name, ImageType_value)
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x9e, 0x5c, 0xdc,
	0xce, 0x45, 0xa9, 0x29, 0xa9, 0x79, 0x25, 0x99, 0x89, 0x39, 0xc5, 0x42, 0xf2, 0x5c, 0xdc, 0x8e,
	0x39, 0xe9, 0xf9, 0x39, 0x99, 0x89, 0xf1, 0x8e, 0xbe, 0x9e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x5c, 0x89, 0x10, 0x21, 0x47, 0x5f, 0x4f, 0x21, 0x49, 0x2e, 0x0e, 0xc7, 0x80, 0x80, 0x78,
	0xe7, 0xfc, 0x94, 0x54, 0x09, 0x26, 0xb0, 0x2c, 0x7b, 0x62, 0x40, 0x00, 0x88, 0xab, 0xa5, 0xc9,
	0xc5, 0xe9, 0x99, 0x9b, 0x98, 0x9e, 0x1a, 0x52, 0x59, 0x90, 0x2a, 0xc4, 0xc1, 0xc5, 0xe2, 0xe6,
	0xe9, 0xe3, 0x2a, 0xc0, 0x20, 0xc4, 0xc9, 0xc5, 0xea, 0xe9, 0xeb, 0xe8, 0xee, 0x2a, 0xc0, 0x28,
	0xc4, 0xce, 0xc5, 0x1c, 0x1a, 0xe4, 0x23, 0xc0, 0x94, 0x04, 0xb1, 0xdd, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x31, 0xa2, 0x8f, 0x1e, 0x93, 0x00, 0x00, 0x00,
}
